// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type ChainMeta struct {
	MostRecentEpoch       string `json:"mostRecentEpoch"`
	MostRecentBlockHeight string `json:"mostRecentBlockHeight"`
	MostRecentTps         string `json:"mostRecentTPS"`
}

type NumberOfCandidates struct {
	TotalCandidates    int `json:"totalCandidates"`
	ConsensusDelegates int `json:"consensusDelegates"`
}

type Productivity struct {
	Production         string `json:"production"`
	ExpectedProduction string `json:"expectedProduction"`
}

type Reward struct {
	BlockReward     string `json:"blockReward"`
	EpochReward     string `json:"epochReward"`
	FoundationBonus string `json:"foundationBonus"`
}

type RewardDistribution struct {
	VoterAddress string `json:"voterAddress"`
	Amount       string `json:"amount"`
}

type VotingInfo struct {
	VoterAddress  string `json:"voterAddress"`
	WeightedVotes string `json:"weightedVotes"`
}
